const TITLE_YEAR_LIBRARY_SIZE = 60;

const CELLAR_TITLES = [
  'Château Margaux',
  'Sassicaia',
  'Barolo Cannubi',
  'Vega Sicilia Unico',
  'Domaine de la Romanée-Conti La Tâche',
  'Penfolds Grange',
  'Opus One',
  'Tignanello',
  'Château d’Yquem',
  'Gaja Barbaresco',
  'Ridge Monte Bello',
  'Château Haut-Brion',
  'Ornellaia',
  'Kistler Chardonnay',
  'Krug Grande Cuvée',
  'Château Cheval Blanc',
  'Pingus',
  'Harlan Estate',
  'Masseto',
  'Château Lafite Rothschild',
  'Giacomo Conterno Monfortino',
  'Screaming Eagle',
  'Château Palmer',
  'Quinta do Noval Nacional',
  'Domaine Leflaive Montrachet',
  'Caymus Special Selection',
  'Château Mouton Rothschild',
  'Bruno Giacosa Falletto',
  'Catena Zapata Adrianna',
  'Château Pétrus',
  'Henschke Hill of Grace',
  'Château Lynch-Bages',
  'Antinori Solaia',
  'Shafer Hillside Select',
  'Château Cos d’Estournel',
  'Biondi-Santi Brunello',
  'Cloudy Bay Sauvignon Blanc',
  'Château Figeac',
  'Alvaro Palacios L’Ermita',
  'Château Ausone',
  'Joseph Phelps Insignia',
  'Château Pontet-Canet',
  'Tenuta San Guido Guidalberto',
  'Château Clinet',
  'Aubert Chardonnay',
  'Château Montrose',
  'Produttori del Barbaresco',
  'Château Léoville Las Cases',
  'Viña Cobos Volturno',
  'Château Ducru-Beaucaillou',
  'E. Guigal La Landonne',
  'Château Beychevelle',
  'Paul Jaboulet Aîné Hermitage La Chapelle',
  'Château Calon-Ségur',
  'Louis Latour Corton-Charlemagne',
  'Château Smith Haut Lafitte',
  'Weingut Keller G-Max',
  'Château Rauzan-Ségla',
  'Trimbach Clos Sainte Hune',
  'Château Clerc Milon',
];

if (CELLAR_TITLES.length !== TITLE_YEAR_LIBRARY_SIZE) {
  throw new Error(
    `Title-year library must have ${TITLE_YEAR_LIBRARY_SIZE} wines`
  );
}

export const titleYearWineLibrary = CELLAR_TITLES.map((title, index) => ({
  _id: `wine-${index + 1}`,
  title,
  year: 1978 + (index % 40),
}));
